pkg: "eu.faircode.email"
display_name: "FairEmail"
arch: "arm64-v8a"
icon: "https://www.google.com/s2/favicons?sz=128&domain=email.faircode.eu"
apk_source:
  type: apkmirror
  org: "marcel-bokhorst"
  slug: "fairemail-open-source-privacy-oriented-email"
  release_slug: "fairemail-privacy-aware-email"
builds:
  - key: "fairemail"
    bundles: ["heval"]
