pkg: "com.google.android.inputmethod.latin"
display_name: "Gboard"
arch: "arm64-v8a"
icon: "https://cdn.simpleicons.org/google/4285F4"
apk_source:
  type: apkmirror
  org: "google-inc"
  slug: "gboard"
  release_slug: "gboard-the-google-keyboard"
builds:
  - key: "gboard"
    bundles: ["jasonwu"]
    exclude:
      - "Zhuyin Bottom Row Key Sizes"
      - "Zhuyin Quick Traditional/Simplified Toggle"
      - "Zhuyin Slide Input"
