pkg: "app.simple.inure.play"
display_name: "inure-PlayStore"
arch: "arm64-v8a"
icon: "https://files.svgcdn.io/arcticons/inure.svg"
apk_source:
  type: github
  owner: "Hamza417"
  repo: "Inure"
  asset_hint: "play"
  tag_template: "build{version}"
builds:
  - key: "inure-play"
    bundles: ["rushi"]
